---
title: "HW5"
author: "NZ"
date: "2025-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Homewrok5

Nicolás Zapata

### 1
Assign to the variable n_dims a single random integer between 3 and 10.

```{r, eval=TRUE, echo=TRUE}
n_dims <- sample(3:10, size=1)
print(n_dims)

```

Create a vector of consecutive integers from 1 to n_dims2
```{r, eval=TRUE, echo=TRUE}
my_vector <- seq(1:n_dims^2)

```

Use the sample function to randomly reshuffle these values.
```{r, eval=TRUE, echo=TRUE}
matrix1 <- matrix(sample(my_vector), nrow=n_dims)
# print out the matrix
print(matrix1) 
```

Find a function in r to transpose the matrix
``` {r, eval=TRUE, echo=TRUE}
transposed_matrix1 <- t(matrix1)
print(transposed_matrix1)
```

Calculate the sum and the mean of the elements in the first row and then the last row.
```{r, eval=TRUE, echo=TRUE}
# mean first row
firstrow_mean <- mean(matrix1[1,])
print(firstrow_mean) 
# sum  first row
firstrow_sum <- sum(matrix1[1,])
print(firstrow_sum)
```

```{r, eval=TRUE, echo=TRUE}
# mean last row 
lastrow_mean <- mean(matrix1[n_dims,])
print(lastrow_mean)
# sum last row
lastrow_sum <- sum(matrix1[n_dims,]) 
print(lastrow_sum)
 
```








