---
title: "HW_10_NZ"
author: "NZ"
date: "2025-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Homewrok10

Advanced ggplotting

Nicolás Zapata

```{r, eval=TRUE, echo=TRUE}
# I started by loading the necessary packages 
library(tidyr)
library(ggbeeswarm)
library(cowplot)
library(ggridges)
library(ggplot2)
library(tidyverse)
library(skimr)
```

```{r, eval=TRUE, echo=TRUE}
# I explored the available data. I will use the data from the rolling stone album rankigs.

rolling_stone <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-05-07/rolling_stone.csv')

str(rolling_stone)
head(rolling_stone)
skimr::skim(rolling_stone) 

# Check the data, especially the column names.

colnames(rolling_stone)

```

```{r, eval=TRUE, echo=TRUE}
# I tested different graphs

boxplot_plot <- ggplot(rolling_stone_clean, aes(x = genre, y = rank_2020, fill = genre)) +
  geom_boxplot(outlier.colour = "red", outlier.size = 2, alpha = 0.6) +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  labs(title = "Ranking album (2020)",
       x = "Genre",
       y = "Ranking") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(boxplot_plot)
```

```{r, eval=TRUE, echo=TRUE}
violin_plot <- ggplot(rolling_stone_clean, aes(x = genre, y = rank_2020, fill = genre)) +
  geom_violin(alpha = 0.6) +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  labs(title = "Ranking album (2020)",
       x = "Genre",
       y = "Ranking") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(violin_plot)
```

```{r, eval=TRUE, echo=TRUE}
library(ggridges)
ridgeline_plot <- ggplot(rolling_stone_clean, aes(y = genre, x = rank_2020, fill = genre)) +
  geom_density_ridges(alpha = 0.6) +
  scale_fill_brewer(palette = "Set2") +
  theme_minimal() +
  labs(title = "Ranking album (2020)",
       x = "Ranking",
       y = "Genre") +
  theme(axis.text.y = element_text(size = 8))

print(ridgeline_plot)
```

```{r, eval=TRUE, echo=TRUE}
combined_plot <- plot_grid(boxplot_plot, violin_plot, labels = "AUTO")
print(combined_plot)
```

```{r, eval=TRUE, echo=TRUE}

genre_counts <- table(rolling_stone_clean$genre)

waffle_plot <- waffle(genre_counts, rows = 5, title = "Album distribution per muscial genre") +
  theme(plot.title = element_text(size = 16))

print(waffle_plot)
```






